version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: financli-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: financli
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - financli-network

volumes:
  mongodb_data:

networks:
  financli-network:
    driver: bridge